packages:
  - "apps/*"
  - "packages/*"

engineStrict: true
pmOnFail: error

allowBuilds:
  "@prisma/engines@7.8.0": true
  "@scarf/scarf": false
  "prisma@7.8.0": true
  sharp: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - "turbo@2.10.5"
  - "typescript@6.0.3"
