import type { FeatureName } from "@fas/feature";
import type {
  LambdaFeatureGroupId,
  LambdaFeatureScale,
  LambdaFeatureWeightEntry,
} from "./lambda-parameter-set.js";

function weight(
  featureName: FeatureName,
  group: LambdaFeatureGroupId,
  side: LambdaFeatureWeightEntry["side"],
  scale: LambdaFeatureScale,
  value: number,
): LambdaFeatureWeightEntry {
  return Object.freeze({
    featureName,
    group,
    side,
    scale,
    weight: value,
  });
}

export const FEATURE_ENRICHED_LAMBDA_FEATURE_WEIGHTS = Object.freeze([
  weight("goalsScoredRateHome", "attack", "home", "unitCentered", 0.08),
  weight("goalsScoredRateAway", "attack", "away", "unitCentered", 0.08),
  weight("attackEfficiencyHome", "attack", "home", "unitCentered", 0.06),
  weight("attackEfficiencyAway", "attack", "away", "unitCentered", 0.06),
  weight("chanceCreationHome", "attack", "home", "unitCentered", 0.05),
  weight("chanceCreationAway", "attack", "away", "unitCentered", 0.05),
  weight("possessionHome", "attack", "home", "unitCentered", 0.03),
  weight("possessionAway", "attack", "away", "unitCentered", 0.03),
  weight("momentumHome", "attack", "home", "unitCentered", 0.04),
  weight("momentumAway", "attack", "away", "unitCentered", 0.04),
  weight("recentFormHome", "attack", "home", "unitCentered", 0.05),
  weight("recentFormAway", "attack", "away", "unitCentered", 0.05),
  weight("formAtHomeHome", "attack", "home", "unitCentered", 0.04),
  weight("formAtHomeAway", "attack", "away", "unitCentered", 0.04),
  weight("formOnRoadHome", "attack", "home", "unitCentered", 0.04),
  weight("formOnRoadAway", "attack", "away", "unitCentered", 0.04),
  weight("playerAttackContributionHome", "attack", "home", "unitCentered", 0.07),
  weight("playerAttackContributionAway", "attack", "away", "unitCentered", 0.07),
  weight("clubAttackStrengthHome", "attack", "home", "unitCentered", 0.06),
  weight("clubAttackStrengthAway", "attack", "away", "unitCentered", 0.06),
  weight("formStrengthHome", "attack", "home", "unitCentered", 0.04),
  weight("formStrengthAway", "attack", "away", "unitCentered", 0.04),
  weight("goalDifferenceStrengthHome", "attack", "home", "unitCentered", 0.04),
  weight("goalDifferenceStrengthAway", "attack", "away", "unitCentered", 0.04),
  weight("goalsConcededRateHome", "defence", "home", "unitCentered", 0.06),
  weight("goalsConcededRateAway", "defence", "away", "unitCentered", 0.06),
  weight("disciplineRiskHome", "defence", "home", "unitCentered", 0.03),
  weight("disciplineRiskAway", "defence", "away", "unitCentered", 0.03),
  weight("xgDefenseQualityHome", "defence", "home", "unitCentered", 0.08),
  weight("xgDefenseQualityAway", "defence", "away", "unitCentered", 0.08),
  weight("clubDefensiveStrengthHome", "defence", "home", "unitCentered", 0.05),
  weight("clubDefensiveStrengthAway", "defence", "away", "unitCentered", 0.05),
  weight("xgAttackQualityHome", "xg", "home", "unitCentered", 0.12),
  weight("xgAttackQualityAway", "xg", "away", "unitCentered", 0.12),
  weight("finishingEfficiencyHome", "xg", "home", "unitCentered", 0.08),
  weight("finishingEfficiencyAway", "xg", "away", "unitCentered", 0.08),
  weight("clubStrengthHome", "clubStrength", "home", "unitCentered", 0.06),
  weight("clubStrengthAway", "clubStrength", "away", "unitCentered", 0.06),
  weight("pointsPerMatchHome", "clubStrength", "home", "unitCentered", 0.05),
  weight("pointsPerMatchAway", "clubStrength", "away", "unitCentered", 0.05),
  weight(
    "availabilityPenaltyHome",
    "playerAvailability",
    "home",
    "availabilityPenalty",
    -0.1,
  ),
  weight(
    "availabilityPenaltyAway",
    "playerAvailability",
    "away",
    "availabilityPenalty",
    -0.1,
  ),
  weight(
    "playerAvailabilityImpactHome",
    "playerAvailability",
    "home",
    "availabilityPenalty",
    -0.12,
  ),
  weight(
    "playerAvailabilityImpactAway",
    "playerAvailability",
    "away",
    "availabilityPenalty",
    -0.12,
  ),
  weight(
    "keyPlayerAvailabilityHome",
    "playerAvailability",
    "home",
    "availabilityPenalty",
    -0.08,
  ),
  weight(
    "keyPlayerAvailabilityAway",
    "playerAvailability",
    "away",
    "availabilityPenalty",
    -0.08,
  ),
  weight(
    "squadAvailabilityScoreHome",
    "playerAvailability",
    "home",
    "unitCentered",
    0.06,
  ),
  weight(
    "squadAvailabilityScoreAway",
    "playerAvailability",
    "away",
    "unitCentered",
    0.06,
  ),
  weight(
    "goalkeeperReliabilityHome",
    "playerAvailability",
    "home",
    "unitCentered",
    0.05,
  ),
  weight(
    "goalkeeperReliabilityAway",
    "playerAvailability",
    "away",
    "unitCentered",
    0.05,
  ),
  weight("fatigueIndexHome", "matchContext", "home", "percentCentered", -0.08),
  weight("fatigueIndexAway", "matchContext", "away", "percentCentered", -0.08),
  weight("rotationPressureHome", "matchContext", "home", "unitCentered", -0.05),
  weight("rotationPressureAway", "matchContext", "away", "unitCentered", -0.05),
  weight("venueAdvantage", "matchContext", "home", "unitCentered", 0.04),
  weight("homeStability", "matchContext", "home", "unitCentered", 0.03),
  weight("scheduleAdvantage", "matchContext", "shared", "signedDays", 0.05),
  weight("knockoutContext", "matchContext", "shared", "unitCentered", 0.02),
] satisfies readonly LambdaFeatureWeightEntry[]);

export const FEATURE_ENRICHED_LAMBDA_PARAMETER_SET = Object.freeze({
  baseRate: 1.3,
  min: 0.05,
  max: 5,
  homeAttackShare: 0.6,
  awaySuppressShare: 0.4,
  ratingScale: 50,
  defenseFloor: 0.05,
  featureWeights: FEATURE_ENRICHED_LAMBDA_FEATURE_WEIGHTS,
});
