export {
  createFeature,
  FeatureValidationError,
} from "./domain/feature.js";
export type {
  CreateFeatureInput,
  Feature,
  FeatureName,
} from "./domain/feature.js";
export {
  createFeatureBundle,
  FEATURE_MODEL_VERSION,
  FeatureBundleValidationError,
} from "./domain/feature-bundle.js";
export type {
  CreateFeatureBundleInput,
  FeatureBundle,
  FeatureBundleStatus,
} from "./domain/feature-bundle.js";
export {
  FeatureExtractionError,
  FeatureExtractor,
} from "./extraction/feature-extractor.js";
export type { FeatureExtractionErrorCode } from "./extraction/feature-extractor.js";
export {
  BASELINE_ATTACK,
  BASELINE_CLUB_GOALS_AGAINST,
  BASELINE_CLUB_GOALS_FOR,
  BASELINE_DEFENSE,
  BASELINE_GOALKEEPER_GOALS_CONCEDED_PER_MATCH,
  BASELINE_GOALKEEPER_SAVES_PER_MATCH,
  BASELINE_LEAGUE_SIZE,
  BASELINE_MANAGER_TENURE_DAYS,
  BASELINE_PLAYER_CONTRIBUTION_PER_MATCH,
  BASELINE_PLAYER_MINUTES_PER_MATCH,
  BASELINE_PLAYER_RATING,
  BASELINE_SHOTS_AGAINST,
  BASELINE_SHOTS_FOR,
  BASELINE_XG_AGAINST,
  BASELINE_XG_FOR,
  clamp,
  computeAttackEfficiency,
  computeAttackRating,
  computeAvailabilityPenalty,
  computeChanceCreation,
  computeClubAttackStrength,
  computeClubDefensiveStrength,
  computeClubGoalDifferenceStrength,
  computeClubLeagueStrength,
  computeClubPointsPerMatch,
  computeClubStrength,
  computeClubVenueStrength,
  computeDefenseRating,
  computeDisciplineRisk,
  computeFatigueIndex,
  computeFinishingEfficiency,
  computeGoalkeeperReliability,
  computeH2hLean,
  computeAsianHandicapLean,
  computeHomeStability,
  computeImpliedProbabilities,
  computeKnockoutContext,
  computeManagerStability,
  computeMarketConsensus,
  computeMarketLean,
  computeMarketVolatility,
  computeMomentum,
  computePlayerAttackContribution,
  computePlayerAvailabilityImpact,
  computePossessionDominance,
  computeRecentFormScore,
  computeReverseLineMovement,
  computeRotationPressure,
  computeSharpSupport,
  computeSquadAvailabilityScore,
  computeSteamMove,
  computeScheduleAdvantage,
  computeXgAttackQuality,
  computeXgDefenseQuality,
  computeXgDominance,
  DEFAULT_HOME_ADVANTAGE,
  DEFAULT_POSITION_AVAILABILITY_WEIGHT,
  isKeyPlayerAbsence,
  KEY_PLAYER_CONTRIBUTION_THRESHOLD,
  mean,
  MOMENTUM_DECAY,
  positionAvailabilityWeight,
  roundFeature,
  shrink,
  SHRINK_K,
  VENUE_ADVANTAGE_SCORE,
} from "./extraction/feature-math.js";
